---
editor: 
  markdown: 
    wrap: 72
---

# Interactive graph

<html lang="en">

<head>

<meta charset="UTF-8">

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>CO2 Emissions Bar Chart</title>

```{=html}
<script src="https://d3js.org/d3.v7.min.js"></script>
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.7.2/nouislider.min.css">

```{=html}
<script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.7.2/nouislider.min.js"></script>
```
```{=html}
<style>
    .chart {
      display: flex;
      align-items: center;
    }
    .bar {
      fill: steelblue;
    }
    
    .bar:hover{
      fill: orange
    }
    .axis text {
      font-size: 12px;
    }
    
    #slider1 .noUi-target {
    border: none;
    box-shadow: none;
    background: #e9ecef;
    height: 8px;
    margin-top: -20px; /* Reduce gap between chart and slider */
    }
    
    #slider1 .noUi-connect {
        background: #007BFF;
        height: 16px;
    }
    
    #slider1 .noUi-handle {
        width: 30px;
        height: 29px;
        border-radius: 100%;
        background: #007BFF;
        border: none;
        box-shadow: none;
        cursor: pointer;
        right: -8px; /* Center the handle */
    }
    
    /* Remove default handle styling */
    #slider1 .noUi-handle::before,
    #slider1 .noUi-handle::after {
        display: none;
    }
    
    #slider2 .noUi-target {
    border: none;
    box-shadow: none;
    background: #e9ecef;
    height: 8px;
    margin-top: -20px; /* Reduce gap between chart and slider */
    }
    
    #slider2 .noUi-connect {
        background: #007BFF;
        height: 16px;
    }
    
    #slider2 .noUi-handle {
        width: 30px;
        height: 29px;
        border-radius: 100%;
        background: #007BFF;
        border: none;
        box-shadow: none;
        cursor: pointer;
        right: -8px; /* Center the handle */
    }
    
    /* Remove default handle styling */
    #slider2 .noUi-handle::before,
    #slider2 .noUi-handle::after {
        display: none;
    }
    
    .tooltip{
      line-height: 1;
      font-weight: bold;
      padding: 12px;
      background: rgba(0, 0, 0, 0.8);
      color: #fff;
      border-radius: 2px;
    }
    
   

  </style>
```
</head>

<body>

<h2 style="text-align: center;">

Primary Energy Production

</h2>

<p>Select the type of energy (fossil, nuclear, or renewable)you are
interested from the dropdown menu. You can scroll the slider to check
for any period of time within the year 1949 to 2023. Pay attention to
the y-axis scale when selecting different types of energy.</p>

<label for="sourceDropdown2">Select Source:</label>
<select id="sourceDropdown2"></select> <br><br>

::: {#chart2}
:::

::: {#slider2}
:::

<p>Notice that nuclear sources have been increasing in the past 30 to 40
years, and renewable source has been given more attention in the recent
decades. Yet, we see that fossil fuels are still the main source of
energy and are still rising in production.</p>

<br> <br>

<h2 style="text-align: center;">

CO<sub>2</sub> Emissions

</h2>

<p>Select the type of carbon dioxide emission sources you are interested
from the dropdown menu. You can scroll the slider to check for any
period of time within the year 1973 to 2023. Pay attention to the y-axis
scale when selecting different types of emission sources.</p>

<label for="sourceDropdown1">Select Source:</label>
<select id="sourceDropdown1"></select> <br> <br>

::: {#chart1}
:::

::: {#slider1}
:::

```{=html}
<script src="./scripts/myscript.js">
    
</script>
```
<p>Notice that the carbon dioxide emission due to coal, one of the major
source of emission, has been decreasing in the past 2 decades, while
emission due to other major source, petroleum, gasoline, and natural
gas, has experienced limited control, if not rising.</p>

</body>

</html>
